server:
  port: 8080
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true

  datasource:
    url: jdbc:mysql://localhost:3306/jpa
    username: root
    password: Theodore1@
    driver-class-name: com.mysql.cj.jdbc.Driver
